# Base image
FROM node:<%- nodeVersion %><%- production ? '-alpine' : '-slim' %>

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

<%_ if (production) { _%>
# Install only production dependencies for smaller image size
RUN npm ci --only=production
<%_ } else { _%>
# Install all dependencies
RUN npm install
<%_ } _%>

# Bundle app source
COPY . .


<%_ if (production) { _%>
# Set NODE_ENV
ENV NODE_ENV=production
<%_ } _%>

EXPOSE <%- containerPort %>

# Command to run the application
CMD ["npm", "start"]